apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: bigdata
spec:
  selector:
    app: kafka
  ports:
    - name: host
      port: 19092
    - name: internal
      port: 19093
    - name: controller
      port: 19094
