apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: bigdata
data:
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_NODE_ID: "1"
  KAFKA_CLUSTER_ID: "abcdefghijklmnopqrstuv"   # string bất kỳ, 22 chars
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:19094"

  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:19093,CONTROLLER://0.0.0.0:19094"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:19093"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

  KAFKA_LOG_DIRS: "/var/lib/kafka/data"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"